hero_image:
  type: string
  default: "https://stemaway-updivision-urlsigner.storage.googleapis.com/original/2X/3/32487731acffa48c311f9c70541da9babeb63149.png"
  description:
    en:
      'The source url for the hero image. Tip: You can upload an image to your main theme and use the url from that,
      but make sure that you do not use "Uploads" section of this component. Any uploads added to this component will be
      deleted whenever it is updated.'
hero_title:
  type: string
  default: "The Launchpad for your STEM Career"
  description: Main Title of Homepage Banner
hero_subtitle:
  type: string
  default: "FREE Career tools for students and junior professionals"
  description: Subtitle of Homepage Banner
hero_links_title:
  type: string
  default: "Quick Links"
  description: Title of the heading for the set of links on the homepage banner (default is Quick Links).
hero_link_1_title:
  type: string
  default: Virtual Internship Info
  description: Title of first link on homepage banner
hero_link_1_icon:
  type: string
  default: "certificate"
  description: Find icons at https://fontawesome.com/icons?d=gallery&m=free and use name underneath icon (do not include fa-prefix)
hero_link_1_url:
  type: string
  default: https://stemaway.com/apply
  description: URL link for first link on homepage banner
hero_link_2_title:
  type: string
  default: Corporate Members
  description: Title of second link on homepage banner
hero_link_2_icon:
  type: string
  default: "briefcase"
  description: Find icons at https://fontawesome.com/icons?d=gallery&m=free and use name underneath icon (do not include fa-prefix)
hero_link_2_url:
  type: string
  default: https://stemaway.com/corporate-partners
  description: URL link for second link on homepage banner
hero_link_3_title:
  type: string
  default: About Us
  description: Title of third link on homepage banner
hero_link_3_icon:
  type: string
  default: "users"
  description: Find icons at https://fontawesome.com/icons?d=gallery&m=free and use name underneath icon (do not include fa-prefix)
hero_link_3_url:
  type: string
  default: https://stemaway.com/home
  description: URL link for third link on homepage banner
hero_link_4_title:
  type: string
  default: Showcase
  description: Title of fourth link on homepage banner
hero_link_4_icon:
  type: string
  default: "store"
  description: Name of FontAwesome Icon for link 3. (do not include fa- prefix)
hero_link_4_url:
  type: string
  default: https://stemaway.com/c/showcase/65
  description: URL link for fourth link on homepage banner
